// const coverLetterPool = [
//     {
//         id: 0,
//         letter: [
//             "first ",
//             "first ",
//             "first ",
//         ],
//     },
//     {
//         id: 1,
//         letter: [
//             "second ",
//             "second ",
//             "second ",
//         ],
//     },
//     {
//         id: 2,
//         letter: [
//             "third ",
//             "third ",
//             "third ",
//         ],
//     },
// ];

// export { coverLetterPool };


const coverLetterPool = [
    {
    letter: [
            "Dear H",
            "iring ",
            "Manage",
            "r, I a",
            "m writ",
            "ing to",
            " expre",
            "ss my ",
            "intere",
            "st in ",
            "the op",
            "en pos",
            "ition ",
            "at you",
            "r este",
            "emed o",
            "rganiz",
            "ation.",
            " With ",
            "my div",
            "erse s",
            "kill s",
            "et and",
            " stron",
            "g wor",
            "k eth",
            "ic, I",
            " beli",
            "eve ",
            "I can",
            " cont",
            "ribut",
            "e to ",
            "the s",
            "ucces",
            "s of ",
            "your ",
            "team. ",
            "I am c",
            "onfid",
            "ent i",
            "n my ",
            "abil",
            "ity t",
            "o ada",
            "pt to",
            " new ",
            "chal",
            "leng",
            "es an",
            "d wor",
            "k col",
            "labo",
            "rati",
            "vely ",
            "with ",
            "coll",
            "eagu",
            "es to",
            " achi",
            "eve c",
            "ommo",
            "n goa",
            "ls. M",
            "y pas",
            "sion ",
            "for e",
            "xcel",
            "lenc",
            "e and",
            " comm",
            "itme",
            "nt to",
            " achi",
            "evin",
            "g res",
            "ults ",
            "make ",
            "me a",
            " valu",
            "able ",
            "asse",
            "t. I ",
            "look ",
            "forwa",
            "rd to",
            " the ",
            "oppo",
            "rtuni",
            "ty to",
            " disc",
            "uss f",
            "urthe",
            "r how",
            " my b",
            "ackgr",
            "ound ",
            "align",
            "s wi",
            "th yo",
            "ur or",
            "gani",
            "zati",
            "on's ",
            "need",
            "s."
        ],
      },
    ];

export { coverLetterPool };