const coverLetterObj = [
    {
        id: 0,
        letter: 
        // [
        //     "Dea",
        //     "r H",
        //     "iri",
        //     "ng ",
        //     "Man",
        //     "age",
        //     "r, ",
        //     "I a",
        //     "m w",
        //     "rit",
        //     "ing",
        //     " to",
        //     " ex",
        //     "pre",
        //     "ss ",
        //     "my ",
        //     "int",
        //     "ere",
        //     "st ",
        //     "in ",
        //     "the",
        //     " op",
        //     "en ",
        //     "pos",
        //     "iti",
        //     "on ",
        //     "at ",
        //     "you",
        //     "r e",
        //     "ste",
        //     "eme",
        //     "d o",
        //     "rga",
        //     "niz",
        //     "ati",
        //     "on.",
        //     " Wi",
        //     "th ",
        //     "my ",
        //     "div",
        //     "ers",
        //     "e s",
        //     "kil",
        //     "l s",
        //     "et ",
        //     "and",
        //     " st",
        //     "ron",
        //     "g w",
        //     "ork",
        //     " et",
        //     "hic",
        //     ", I",
        //     " be",
        //     "lie",
        //     "ve ",
        //     "I c",
        //     "an ",
        //     "con",
        //     "tri",
        //     "but",
        //     "e t",
        //     "o t",
        //     "he ",
        //     "suc",
        //     "ces",
        //     "s o",
        //     "f y",
        //     "our",
        //     " te",
        //     "am.",
        //     " I ",
        //     "am ",
        //     "con",
        //     "fid",
        //     "ent",
        //     " in",
        //     " my",
        //     " ab",
        //     "ili",
        //     "ty ",
        //     "to ",
        //     "ada",
        //     "pt ",
        //     "to ",
        //     "new",
        //     " ch",
        //     "all",
        //     "eng",
        //     "es ",
        //     "and",
        //     " wo",
        //     "rk ",
        //     "col",
        //     "lab",
        //     "ora",
        //     "tiv",
        //     "ely",
        //     " wi",
        //     "th ",
        //     "col",
        //     "lea",
        //     "gue",
        //     "s t",
        //     "o a",
        //     "chi",
        //     "eve",
        //     " co",
        //     "mmo",
        //     "n g",
        //     "oal",
        //     "s. ",
        //     "My ",
        //     "pas",
        //     "sio",
        //     "n f",
        //     "or ",
        //     "exc",
        //     "ell",
        //     "enc",
        //     "e a",
        //     "nd ",
        //     "com",
        //     "mit",
        //     "men",
        //     "t t",
        //     "o a",
        //     "chi",
        //     "evi",
        //     "ng ",
        //     "res",
        //     "ult",
        //     "s m",
        //     "ake",
        //     " me",
        //     " a ",
        //     "val",
        //     "uab",
        //     "le ",
        //     "ass",
        //     "et.",
        //     " I ",
        //     "loo",
        //     "k f",
        //     "orw",
        //     "ard",
        //     " to",
        //     " th",
        //     "e o",
        //     "ppo",
        //     "rtu",
        //     "nit",
        //     "y t",
        //     "o d",
        //     "isc",
        //     "uss",
        //     " fu",
        //     "rth",
        //     "er ",
        //     "how",
        //     " my",
        //     " ba",
        //     "ckg",
        //     "rou",
        //     "nd ",
        //     "ali",
        //     "gns",
        //     " wi",
        //     "th ",
        //     "you",
        //     "r o",
        //     "rga",
        //     "niz",
        //     "ati",
        //     "on'",
        //     "s n",
        //     "eed",
        //     "s."
        // ]
        [
            "first cover letter 1",
            "first cover letter 2",
            "first cover letter 3",
            "first cover letter 4",
            "first cover letter 5",
        ],
    },
    {
        id: 1,
        letter: 
        [
            "second cover letter 6",
            "second cover letter 7",
            "second cover letter 8",
            "second cover letter 9",
            "second cover letter 10",
        ],
    },
    {
        id: 2,
        letter: 
        [
            "third cover letter 11",
            "third cover letter 12",
            "third cover letter 13",
            "third cover letter 14",
            "third cover letter 15",
        ],
    },
];



export { coverLetterObj };